Desktop branch
haftamudesta/portfolio-desktop-version pull request #1
Opened 2022-05-05 16:00 UTC by haftamudesta

this is desktop version of the previously implemented mobile version of my portfolio. It is implemented in HTML and CSS.

2022-05-05 16:46 UTC, Ismailco reviewed
Hi @haftamudesta,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

 - You have submitted a project, that has no professional README, you can use this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) to create a README and submit a new review request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-05-05 18:01 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @haftamudesta,

![WeAreSoCloseForrestGIF](https://user-images.githubusercontent.com/50941074/166984348-2889b54f-51d3-4eef-a0d3-cb0994c16b74.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ No linter errors
✅ Correct Github flow

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-05 18:01 UTC, AmaduKamara commented on portfolio.html
> +    </header>
- [ ] It would be nice if you adjust the styling of the navbar, and add the nav links that show on the right just as it's in the Figma template.
- [ ] Also the description text about you in the headline section is running almost across the section. Kindly fix that to match the Figma design and that will make your interface look great. 👍 

**Your design**
![image](https://user-images.githubusercontent.com/50941074/166978962-47a3d359-3dc1-47d0-a575-ed6cda14b147.png)

**The Figma Design Look**
![image](https://user-images.githubusercontent.com/50941074/166979184-452e7156-5e2e-443f-a38c-097b2222d156.png)

2022-05-05 18:01 UTC, AmaduKamara commented on portfolio.html
> +        </div>
- [ ] On a mobile screen, the design for this section looks great but on a desktop screen, the image is too small and there is too much white space between the image and the right texts. Please fix that to match the Figma design. 👍 
- [ ] Kindly add spacing from left and right. Currently, your interface is stretched 100% and it looks clustered. Kindly and some padding left and right on desktop screens

**Your Design**
![image](https://user-images.githubusercontent.com/50941074/166980788-498529ac-110e-4901-8a11-c0d15cbce228.png)


**The Figma Design**
![image](https://user-images.githubusercontent.com/50941074/166980270-6810c616-dfc9-4088-948a-cc2f54ad64c5.png)

2022-05-05 18:01 UTC, AmaduKamara commented on portfolio.html
> +    </div>
- [ ] On this section, kindly give some space from the top of the About Me text and also move the section from the left in some more space to match your design with the Figma design. It's not looking professional but I'm sure if you fix that, you will see how great your app will be. 👍 
- [ ] Kindly add left and right spacing just as it's in the Figma design.

**Your design**
![image](https://user-images.githubusercontent.com/50941074/166981851-fb4a0c43-bf71-40dd-b45a-6b9014273346.png)

**The Figma design**

![image](https://user-images.githubusercontent.com/50941074/166982039-a5a8d4eb-797a-40e8-9e00-21a11e9119a1.png)

2022-05-05 18:01 UTC, AmaduKamara commented on portfolio.html
> +        </form>
- [ ] The form fields design looks great on mobile screens but on desktop screens, things don't look as great as before. Kindly adjust the spacing between the input fields. Please reduce the spacing between them
- [ ] Also, I noticed the text on the left is seated in the top left corner just like the other areas of your design. Kindly bring it down a little and also from the left a bit in order to match your design with the Figma template. 👍 

**Your design**

![image](https://user-images.githubusercontent.com/50941074/166983477-fdce663e-a889-4ff0-8cb6-35b74fa3b4b0.png)

**The Figma Design**

![image](https://user-images.githubusercontent.com/50941074/166983717-574fff44-123c-47f7-a11a-9a968af2375d.png)

2022-05-05 23:01 UTC, CollinsTatang requested changes
Hi @haftamudesta , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
 

- [ ] Please try to match the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471) design as requested by the previous code reviewer.
### **Take A Look**

https://user-images.githubusercontent.com/55596970/167040496-6181483b-3b69-4a20-85ce-24a31ff5c9bb.mp4


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 16:05 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @haftamudesta , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 17:38 UTC, merged